### PR TITLE
Add work_reuse tag

### PR DESCRIPTION
**Pull request by tom-tan**
This request adds `work_reuse` tag for [`WorkReuse`](https://www.commonwl.org/v1.2/Workflow.html#WorkReuse).

### CODE REVIEW

**Review by mr-c — COMMENTED** [review]
@tom-tan What if `WorkReuse` was moved to `hints`?

https://github.com/common-workflow-language/cwl-v1.2/commit/a6cb03b3cb67dee2ea644e94b1a57deef4d03c00#diff-bc8aedc9592506dd171277abda2c1207a86260b82508a3a3289cde557e2d5af9R8

@tetron Would that be okay for Arvados?

**Comment by tom-tan** [comment]
> What if `WorkReuse` was moved to `hints`?

A tag `work_reuse` should be for the tests with `WorkReuse` in `requirements`.
Otherwise the platforms accidentally pass the tests with `work_reuse` even though they do not support `WorkReuse`.

**Comment by mr-c** [comment]
> > What if `WorkReuse` was moved to `hints`?
> 
> A tag `work_reuse` should be for the tests with `WorkReuse` in `requirements`.
> Otherwise the platforms accidentally pass the tests with `work_reuse` even though they do not support `WorkReuse`.

Yes, we agree. It appears that these tests weren't designed to test `WorkReuse` specifically so I've asked @tetron if it would be okay to move the `WorkReuse` from `requirements` to `hints` and then we wouldn't need the `work_reuse` tag on the tests. 

Otherwise the `work_reuse` tag should (this PR) should be added.

**Comment by mr-c** [comment]
@tom-tan in https://github.com/common-workflow-language/cwl-v1.2/commit/a6cb03b3cb67dee2ea644e94b1a57deef4d03c00 @tetron wrote

> Disable work reuse on time limit tests (implementations such as
Arvados doesn't consider time limits when sharing/reusing tasks,
causes false negatives when one test is expecting success and another
test is expecting failure on the same underlying command.)

**Comment by tom-tan** [comment]
It's OK for me to move the `work_reuse` tag in the tests for `timelimit` to `hints` but it would be nice if there are other tests for `work_reuse`.
Currently `work_reuse` is only used in the tests for `timelimit`.

**Review by mr-c — APPROVED** [review]

**Comment by mr-c** [comment]
Thanks @tom-tan ; I made a separate issue about softening the need for `WorkReuse`; as for testing `WorkReuse` properly, that might be a little difficult! See https://github.com/common-workflow-language/cwl-v1.2/issues/86 for an idea.

**Pull request merged**
