### PR TITLE
Fix minor typos

### PR DESCRIPTION
**Pull request by joshmoore**
Propagate changes from https://github.com/common-workflow-language/schema_salad/pull/366 to the v1.2 spec.

### CODE REVIEW

**Review by mr-c — APPROVED** [review]

**Comment by joshmoore** [comment]
@mr-c: shall I force-push this branch with all of my commits signed?

**Comment by mr-c** [comment]
> @mr-c: shall I force-push this branch with all of my commits signed?

Yes, please n

**Comment by joshmoore** [comment]
Done

**Review by mr-c — APPROVED** [review]

**Comment by mr-c** [comment]
@joshmoore Alas it says
> The committer email address is not verified. 

Is `josh@glencoesoftware.com` not associated with your GitHub profile?

**Comment by joshmoore** [comment]
Well that's weird! My 15-year old email address had been silently be de-verified. I re-verified. Did that change the status for you?

**Comment by mr-c** [comment]
All good now!

**Pull request merged**
