### PR TITLE
More defaults

### PR DESCRIPTION
**Pull request by mr-c**

### CODE REVIEW

**Review by kaushik-work — COMMENTED** [review]
These go into effect for 1.2? Trying to think of consequences for existing 1.0, 1.1 implementations.

**Comment by mr-c** [comment]
> These go into effect for 1.2? Trying to think of consequences for existing 1.0, 1.1 implementations.

These were always the defaults in the text, but not in the schema as schema-salad didn't get a default field until more recently.

**Comment by mr-c** [comment]
@kaushik-work see https://github.com/common-workflow-language/schema_salad/issues/124#issuecomment-737115114

**Comment by mr-c** [comment]
@kaushik-work on a second look, you were right, there is an issue to set these defaults there

Looking at the text for https://www.commonwl.org/v1.2/CommandLineTool.html#ResourceRequirement

> Specify basic hardware resource requirements.

> "min" is the minimum amount of a resource that must be reserved to schedule a job. If "min" cannot be satisfied, the job should not be run.

Later in the table we are told there are default values for `coreMin` (1), `ramMin` (256), `tmpdirMin` (1024), and `outdirMin` (1024), 

> If both "min" and "max" are specified, an implementation may choose to allocate any amount between "min" and "max", with the actual allocation provided in the runtime object.

If I add those defaults values to the schema as I do in this PR, then strictly speaking all the `*Min` fields will always be specified, and this sentence is meaningless.

> If "min" is specified but "max" is not, then "max" == "min" If "max" is specified by "min" is not, then "min" == "max".

Same here. The "min"s will always be specified, so this rule simplifies down to `If "max" is not specified, then "max" == "min"`

> If neither "min" nor "max" is specified for a resource, use the default values below.

So these defaults have to be applied at a different layer than the schema to enable this fallback processing.

Therefore I have updated this PR to add notes to prevent someone else from making the same mistake.

I also added two legitimately missing defaults: `InputBinding.position` default is `0`, and `File.streamable` default is `false`.

**Pull request merged**
