### PR TITLE
all Requirement classes should be static strings

### PR DESCRIPTION
**Pull request by mr-c**

### CODE REVIEW

**Comment by tetron** [comment]
I think this is right.  I'm surprised it wasn't done this way earlier.

**Comment by tetron** [comment]
I think the reason this wasn't "necessary" was special handling in schema salad validation for the `class` field:

https://github.com/common-workflow-language/schema_salad/blob/main/schema_salad/validate.py#L274

I don't know if maybe we should formalize that behavior in addition or instead of this.

**Comment by mr-c** [comment]
Without it then https://github.com/common-workflow-lab/cwljava/issues/31 is a problem. I was going to special case it in the java codegen when I noticed that `class: File` had no issues in the Java clasess

**Comment by mr-c** [comment]
This change also improves the generated HTML

**Comment by mr-c** [comment]
For https://www.commonwl.org/v1.2/CommandLineTool.html#File the `class` is of type "constant value `File`" versus https://www.commonwl.org/v1.2/CommandLineTool.html#DockerRequirement where the class is of type `string`

**Comment by tetron** [comment]
Ok, we should apply this fix if there's no side effects.

If I recall correctly, one of the motivations for special-case handling `class` was just performance, if we validate fields in arbitrary order we can waste a lot of time trying to validate against all the wrong classes.  But that's separate from correctness, which is what this fix helps with.  LGTM.

**Review by tetron — APPROVED** [review]

**Comment by mr-c** [comment]
Thanks! I'm going to test by importing this PR into cwltool and re-running the CWL v1.2 conformance tests first ; then I'll merge

**Pull request closed without merging**
