### PR TITLE
Added CWLObjectType named union

### PR DESCRIPTION
**Pull request by GlassOfWhiskey**
This commit introduces a `CWLObjectType` named union to represent a valid CWL object. Using a more precise union type instead of `Any` allows for a smarter parsing from SALAD auto-generated parsers. In particular, `CWLObjectType` is used to define the type of the `default` directive in CWL `InputParameter` and `WorkflowStepInput` fields. Plus, a `CWLInputFile` type is introduced to represent a CWL jobfiles as `map<string, CWLObjectType>`.

This PR depends on common-workflow-language/schema_salad#672.

### CODE REVIEW

**Review by mr-c — CHANGES_REQUESTED** [review]
Alas, merging this would make significant changes in the HTML rendering of CWL v1.2[.1]

`InputArraySchema` now lists `MapSchema` and `UnionSchema` as acceptable items ; **this is not okay**! 

Adding `CWLObjectType` 

image

**Comment by tetron** [comment]
So, I think this needs to be a 1.3 change.

Introducing this to metaschema_base.yml means introducing new features to CWL, as Michael noted and as I noted over here https://github.com/common-workflow-language/schema_salad/pull/672#pullrequestreview-1495466628

Also, copying a note of that same ticket:

From the Introduction to 1.2:

"inherited records can narrow the types of fields if those fields are re-specified with a matching jsonldPredicate."

I forgot that we did that, but that might mean there is a way to exclude MapSchema and UnionSchema from polluting the CWL 1.2 spec.

**Review by mr-c — CHANGES_REQUESTED** [review]
Alas, I found another change this PR makes: [`CommandInputArraySchema`](https://deploy-preview-220--cwl-v1-2-dev.netlify.app/commandlinetool#CommandInputArraySchema) suddenly gains a `flatten` field. Contrast that to https://www.commonwl.org/v1.2/CommandLineTool.html#CommandInputArraySchema

Same for CommandOutputArraySchema, InputArraySchema, and OutputArraySchema.

Otherwise, the only changes in the rendered spec this PR produces is the addition of a [`CWLObjectType`](https://deploy-preview-220--cwl-v1-2-dev.netlify.app/workflow#CWLObjectType) and reference to `default` now specify this type instead of `Any`.

@GlassOfWhiskey can you use `docAfter` and `docBefore` to ensure that there is no renumbering or re-arranging due to this change?

**Comment by GlassOfWhiskey** [comment]
> Alas, I found another change this PR makes: [`CommandInputArraySchema`](https://deploy-preview-220--cwl-v1-2-dev.netlify.app/commandlinetool#CommandInputArraySchema) suddenly gains a `flatten` field. Contrast that to https://www.commonwl.org/v1.2/CommandLineTool.html#CommandInputArraySchema
> 
> Same for CommandOutputArraySchema, InputArraySchema, and OutputArraySchema.

Yes this is a new feature of `ArraySchema` I added to the Schema SALAD definition. It allows to control if nested arrays should or should not be flattened in a single list. The default behaviour (`true`) was the only one allowed before this PR.

> Otherwise, the only changes in the rendered spec this PR produces is the addition of a [`CWLObjectType`](https://deploy-preview-220--cwl-v1-2-dev.netlify.app/workflow#CWLObjectType) and reference to `default` now specify this type instead of `Any`.

Yes this is the intended behavior of the PR. Maybe we could also think about a third CWL standard for input data in `v1.3`, as now they can be described through the SALAD semantics.

> @GlassOfWhiskey can you use `docAfter` and `docBefore` to ensure that there is no renumbering or re-arranging due to this change?

No problem, but I cannot understand exactly what should happen here. Looking at the docstrings of `docAfter`, `docBefore`, `docParent` and `docChild`, none of these hints seems actually respected in the website documentation generation.

**Comment by GlassOfWhiskey** [comment]
Otherwise, an alternative to the `flatten` field is to create a `UnflattenedArraySchema` in Schema SALAD that extends the `ArraySchema` and defines the `flatten` property.

**Comment by GlassOfWhiskey** [comment]
@tetron suggested a different way to handle nesting. Using the `@list` parameter in the `_container` field of the `jsonldPredicate`, JSON-LD forces ordering and nesting to be preserved. I implemented that logic in all parsers but cpp and dlang, which never flatten lists.
Now the CWL 1.2 documentationshould be ok. For the `doc***` directive, I should understand the semantics more clearly to be able to add them.

**Review by mr-c — COMMENTED** [review]
I can confirm that the `flatten` issue is resolved, thank you @GlassOfWhiskey !

`doc{Parent,Child,After}` are used by [`schema_salad.makedoc.RenderType`](https://github.com/common-workflow-language/schema_salad/blob/68cc3529597da2e7e19e85c1f572bc8c21d8c449/schema_salad/makedoc.py#L369C13-L369C13) to influence the placement.  It is possible they are not working as intended

**Comment by mr-c** [comment]
I can not merge this into `1.2.1_proposed` if it changes numbering for any existing documentation.

**Comment by GlassOfWhiskey** [comment]
But we said to merge it into the codegen branch if I remember correctly. Also because it requires Schema SALAD 1.3, which is not already out afaik

**Comment by GlassOfWhiskey** [comment]
In any case, probably the first PR that we should consider is common-workflow-language/schema_salad#672, as this one heavily depends on it

**Comment by mr-c** [comment]
> But we said to merge it into the codegen branch if I remember correctly. Also because it requires Schema SALAD 1.3, which is not already out afaik

Yep, time to make a post-`1.2.1_proposed` codegen branch. You are right, that I will be less protective of the numbering there :-)

**Comment by mr-c** [comment]
> * Do you want me to keep the updates to the `render.bash` file? One day they will be migrated to the CWL website main branch, bu at the moment there is no `Base.yml` in the CWL main branch. Do you want me to replicate the `Base.yml` thing also in the main branch (the `1.2.1-proposed` one) without the additional features to align the logic?

Sure!

**Review by mr-c — APPROVED** [review]

**Pull request merged**
