### PR TITLE
Adjust behavior of command_input_file_expression

### PR DESCRIPTION
**Pull request by tetron**
Changes it to reference another input parameter instead of using self.
The behavior of processing secondary files patterns in order and being
able to reference earlier ones later is not part of the spec.

This doesn't exactly replicate the previous behavior, because it
introduces a new input parameter, however it does demonstrate the
ability to rename a file and have it staged as a secondary file
without having to use InitialWorkDir.

refs #127

### CODE REVIEW

**Review by mr-c — APPROVED** [review]

**Comment by GlassOfWhiskey** [comment]
@mr-c @tetron @kinow can someone confirm that this issue has been solved by [128](https://github.com/common-workflow-language/cwl-v1.2/pull/128)? For me, it can be closed.

**Comment by mr-c** [comment]
> @mr-c @tetron @kinow can someone confirm that this issue has been solved by [128](https://github.com/common-workflow-language/cwl-v1.2/pull/128)? For me, it can be closed.

Did you mean to post your comment on an issue? This is PR 128..

**Comment by GlassOfWhiskey** [comment]
> > @mr-c @tetron @kinow can someone confirm that this issue has been solved by [128](https://github.com/common-workflow-language/cwl-v1.2/pull/128)? For me, it can be closed.
> 
> Did you mean to post your comment on an issue? This is PR 128..

Yes sorry. It seems to me that this solves #127.

**Comment by kinow** [comment]
> > > @mr-c @tetron @kinow can someone confirm that this issue has been solved by [128](https://github.com/common-workflow-language/cwl-v1.2/pull/128)? For me, it can be closed.
> > 
> > 
> > Did you mean to post your comment on an issue? This is PR 128..
> 
> Yes sorry. It seems to me that this solves #127.

Just read #127, and this PR, and +1 that this solves #127, as this uses an input reference instead of accessing the array element (which relies on chance to work on different CWL implementations, as reported in the linked issue).

**Pull request merged**
