### PR TITLE
Add test for loadListing on outputBinding.

### PR DESCRIPTION
**Pull request by tetron**

### CODE REVIEW

**Review by mr-c — APPROVED** [review]

**Review by mr-c — COMMENTED** [review]
Please sign your commits :-)

> The base branch requires all commits to be signed.

**Comment by tetron** [comment]
Argh, I don't understand why some commits are auto-signed by github and some are not.

**Comment by mr-c** [comment]
@tetron if you make the edit in the browser it is autosigned. Using `git`  you need to follow https://docs.github.com/articles/about-gpg/

**Review by mr-c — APPROVED** [review]

**Comment by tom-tan** [comment]
Please add `id` field.

**Comment by mr-c** [comment]
> Please add `id` field.

Whoops! Thank you for catching that. @tom-tan can you send us a PR to automatically check for well-formed additions to the conformance tests?

**Comment by mr-c** [comment]
Though as noted in https://github.com/common-workflow-language/cwl-v1.2/issues/54 the `id` fields are already partially wrong. And according to https://github.com/common-workflow-language/cwltest/issues/110 we want to get rid of numerical `id`s altogether

**Comment by tom-tan** [comment]
I agree with replacing `id` with `label` if it can be unique in CWL v1.0, v1.1, v1.2 and later and if it is easy to be specified from `cwltest`.
The unique ids will help the platform developers migrating their platforms from v1.0 to v1.1 (also from v1.1 to v1.2, of course).

Anyway, can I send a request or is it better to wait for solving  common-workflow-language/cwltest#110?

**Comment by mr-c** [comment]
> Anyway, can I send a request or is it better to wait for solving [common-workflow-language/cwltest#110](https://github.com/common-workflow-language/cwltest/issues/110)?

Looks like we need to wait for https://github.com/common-workflow-language/cwltest/issues/110 first, but you could help us start by doing items 3, 4, and 5 for `cwltest`?

**Comment by tom-tan** [comment]
OK, I will work on common-workflow-language/cwltest#110 and try to write a schema for the conformance test (I hope JSON schema works with YAML...).

**Comment by mr-c** [comment]
Thank you!

JSON schema doesn't work with YAML but schema-salad does!

--
Michael R. Crusoe

**Comment by tetron** [comment]
@tom-tan I did that already https://github.com/common-workflow-language/cwltest/blob/main/cwltest/cwltest-schema.yml

**Comment by tom-tan** [comment]
Can I add a setting for Github Actions or do you have other preferable CI services for this repository?

**Comment by mr-c** [comment]
> Can I add a setting for Github Actions or do you have other preferable CI services for this repository?

GitHub Actions works for us. Thanks!

**Pull request merged**
